name: Test setup-cloudflared
on:
    push:
        paths:
            - action.yml
            - scripts/**
            - .github/workflows/test.yaml
    pull_request:
        paths:
            - action.yml
            - scripts/**
            - .github/workflows/test.yaml

jobs:
    test-ubuntu:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                version: [latest, 2023.8.1]

        steps:
            - name: Setup cloudflared using setup-cloudflared
              uses: Sparkobbable/setup-cloudflared@main

            - name: Test cloudflared installed by setup-cloudflared using Python HTTP server for 1 minute
              run: timeout 1m python -m http.server 8080 || true

    test-macos:
        runs-on: macos-latest
        strategy:
            fail-fast: false
            matrix:
                version: [latest, 2023.8.1]

        steps:
            - name: Setup cloudflared using setup-cloudflared
              uses: Sparkobbable/setup-cloudflared@main

            - name: Test cloudflared installed by setup-cloudflared using Python HTTP server for 1 minute
              run: |
                  function timeout(){ perl -e 'alarm shift; exec @ARGV' "$@"; }
                  timeout 60 python3 -m http.server 8080 || true

    test-windows:
        runs-on: windows-latest
        strategy:
            fail-fast: false
            matrix:
                version: [latest, 2023.8.1]

        steps:
            - name: Setup cloudflared using setup-cloudflared
              uses: Sparkobbable/setup-cloudflared@main

            - name: Test cloudflared installed by setup-cloudflared using Python HTTP server for 1 minute
              run: |
                  $http_server = Start-Process "python" "-m http.server 8080" -PassThru
                  Wait-Process $http_server.Id -Timeout 60 -ErrorAction Ignore
                  $http_server.CloseMainWindow()
                  Wait-Process $http_server.Id
